/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "operation.h"

bool_t
xdr_DIRENTRY_T(XDR *xdrs, DIRENTRY_T *objp)
{
	register int32_t *buf;

	if (xdrs->x_op == XDR_ENCODE)
	{
		if (!xdr_string(xdrs, &objp->name, MAX_NAME_LENGTH))
			return FALSE;
		buf = XDR_INLINE(xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL)
		{
			if (!xdr_bool(xdrs, &objp->isDirectory))
				return FALSE;
			if (!xdr_int(xdrs, &objp->size))
				return FALSE;
			if (!xdr_int(xdrs, &objp->lastModified))
				return FALSE;
			if (!xdr_bool(xdrs, &objp->filtered))
				return FALSE;
		}
		else
		{
			IXDR_PUT_BOOL(buf, objp->isDirectory);
			IXDR_PUT_LONG(buf, objp->size);
			IXDR_PUT_LONG(buf, objp->lastModified);
			IXDR_PUT_BOOL(buf, objp->filtered);
		}
		return TRUE;
	}
	else if (xdrs->x_op == XDR_DECODE)
	{
		if (!xdr_string(xdrs, &objp->name, MAX_NAME_LENGTH))
			return FALSE;
		buf = XDR_INLINE(xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL)
		{
			if (!xdr_bool(xdrs, &objp->isDirectory))
				return FALSE;
			if (!xdr_int(xdrs, &objp->size))
				return FALSE;
			if (!xdr_int(xdrs, &objp->lastModified))
				return FALSE;
			if (!xdr_bool(xdrs, &objp->filtered))
				return FALSE;
		}
		else
		{
			objp->isDirectory = IXDR_GET_BOOL(buf);
			objp->size = IXDR_GET_LONG(buf);
			objp->lastModified = IXDR_GET_LONG(buf);
			objp->filtered = IXDR_GET_BOOL(buf);
		}
		return TRUE;
	}

	if (!xdr_string(xdrs, &objp->name, MAX_NAME_LENGTH))
		return FALSE;
	if (!xdr_bool(xdrs, &objp->isDirectory))
		return FALSE;
	if (!xdr_int(xdrs, &objp->size))
		return FALSE;
	if (!xdr_int(xdrs, &objp->lastModified))
		return FALSE;
	if (!xdr_bool(xdrs, &objp->filtered))
		return FALSE;
	return TRUE;
}

bool_t
xdr_RANDOMINFO_T(XDR *xdrs, RANDOMINFO_T *objp)
{
	register int32_t *buf;

	if (!xdr_int(xdrs, &objp->firstbyte))
		return FALSE;
	if (!xdr_int(xdrs, &objp->bytenum))
		return FALSE;
	return TRUE;
}

bool_t
xdr_BLOCK_T(XDR *xdrs, BLOCK_T *objp)
{
	register int32_t *buf;

	if (!xdr_bytes(xdrs, (char **)&objp->data.data_val, (u_int *)&objp->data.data_len, MAX_BLOCK_SIZE))
		return FALSE;
	return TRUE;
}
