/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "operation.h"
#include <memory.h>
#include <netinet/in.h>
#include <rpc/pmap_clnt.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>

#ifndef SIG_PF
#define SIG_PF void (*)(int)
#endif

static void
getdir_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union
	{
		int fill;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc)
	{
	case NULLPROC:
		(void)svc_sendreply(transp, (xdrproc_t)xdr_void, (char *)NULL);
		return;

	case GETDIR:
		_xdr_argument = (xdrproc_t)xdr_void;
		_xdr_result = (xdrproc_t)xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *))getdir_1_svc;
		break;

	default:
		svcerr_noproc(transp);
		return;
	}
	memset((char *)&argument, 0, sizeof(argument));
	if (!svc_getargs(transp, (xdrproc_t)_xdr_argument, (caddr_t)&argument))
	{
		svcerr_decode(transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t)_xdr_result, result))
	{
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, (xdrproc_t)_xdr_argument, (caddr_t)&argument))
	{
		fprintf(stderr, "%s", "unable to free arguments");
		exit(1);
	}
	return;
}

static void
cd_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union
	{
		char *changedir_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc)
	{
	case NULLPROC:
		(void)svc_sendreply(transp, (xdrproc_t)xdr_void, (char *)NULL);
		return;

	case CHANGEDIR:
		_xdr_argument = (xdrproc_t)xdr_wrapstring;
		_xdr_result = (xdrproc_t)xdr_bool;
		local = (char *(*)(char *, struct svc_req *))changedir_1_svc;
		break;

	default:
		svcerr_noproc(transp);
		return;
	}
	memset((char *)&argument, 0, sizeof(argument));
	if (!svc_getargs(transp, (xdrproc_t)_xdr_argument, (caddr_t)&argument))
	{
		svcerr_decode(transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t)_xdr_result, result))
	{
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, (xdrproc_t)_xdr_argument, (caddr_t)&argument))
	{
		fprintf(stderr, "%s", "unable to free arguments");
		exit(1);
	}
	return;
}

static void
filecount_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union
	{
		char *filecount_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc)
	{
	case NULLPROC:
		(void)svc_sendreply(transp, (xdrproc_t)xdr_void, (char *)NULL);
		return;

	case FILECOUNT:
		_xdr_argument = (xdrproc_t)xdr_wrapstring;
		_xdr_result = (xdrproc_t)xdr_int;
		local = (char *(*)(char *, struct svc_req *))filecount_1_svc;
		break;

	default:
		svcerr_noproc(transp);
		return;
	}
	memset((char *)&argument, 0, sizeof(argument));
	if (!svc_getargs(transp, (xdrproc_t)_xdr_argument, (caddr_t)&argument))
	{
		svcerr_decode(transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t)_xdr_result, result))
	{
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, (xdrproc_t)_xdr_argument, (caddr_t)&argument))
	{
		fprintf(stderr, "%s", "unable to free arguments");
		exit(1);
	}
	return;
}

static void
ls_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union
	{
		char *openlist_1_arg;
		char *nextlist_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc)
	{
	case NULLPROC:
		(void)svc_sendreply(transp, (xdrproc_t)xdr_void, (char *)NULL);
		return;

	case OPENLIST:
		_xdr_argument = (xdrproc_t)xdr_wrapstring;
		_xdr_result = (xdrproc_t)xdr_bool;
		local = (char *(*)(char *, struct svc_req *))openlist_1_svc;
		break;

	case NEXTLIST:
		_xdr_argument = (xdrproc_t)xdr_wrapstring;
		_xdr_result = (xdrproc_t)xdr_DIRENTRY_T;
		local = (char *(*)(char *, struct svc_req *))nextlist_1_svc;
		break;

	case CLOSELIST:
		_xdr_argument = (xdrproc_t)xdr_void;
		_xdr_result = (xdrproc_t)xdr_bool;
		local = (char *(*)(char *, struct svc_req *))closelist_1_svc;
		break;

	default:
		svcerr_noproc(transp);
		return;
	}
	memset((char *)&argument, 0, sizeof(argument));
	if (!svc_getargs(transp, (xdrproc_t)_xdr_argument, (caddr_t)&argument))
	{
		svcerr_decode(transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t)_xdr_result, result))
	{
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, (xdrproc_t)_xdr_argument, (caddr_t)&argument))
	{
		fprintf(stderr, "%s", "unable to free arguments");
		exit(1);
	}
	return;
}

static void
put_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union
	{
		char *openfiletowrite_1_arg;
		struct BLOCK_T put_nextwrite_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc)
	{
	case NULLPROC:
		(void)svc_sendreply(transp, (xdrproc_t)xdr_void, (char *)NULL);
		return;

	case openfiletowrite:
		_xdr_argument = (xdrproc_t)xdr_wrapstring;
		_xdr_result = (xdrproc_t)xdr_bool;
		local = (char *(*)(char *, struct svc_req *))openfiletowrite_1_svc;
		break;

	case put_nextwrite:
		_xdr_argument = (xdrproc_t)xdr_BLOCK_T;
		_xdr_result = (xdrproc_t)xdr_bool;
		local = (char *(*)(char *, struct svc_req *))put_nextwrite_1_svc;
		break;

	case put_closefile:
		_xdr_argument = (xdrproc_t)xdr_void;
		_xdr_result = (xdrproc_t)xdr_bool;
		local = (char *(*)(char *, struct svc_req *))put_closefile_1_svc;
		break;

	default:
		svcerr_noproc(transp);
		return;
	}
	memset((char *)&argument, 0, sizeof(argument));
	if (!svc_getargs(transp, (xdrproc_t)_xdr_argument, (caddr_t)&argument))
	{
		svcerr_decode(transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t)_xdr_result, result))
	{
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, (xdrproc_t)_xdr_argument, (caddr_t)&argument))
	{
		fprintf(stderr, "%s", "unable to free arguments");
		exit(1);
	}
	return;
}

static void
get_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union
	{
		char *get_openfiletoread_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc)
	{
	case NULLPROC:
		(void)svc_sendreply(transp, (xdrproc_t)xdr_void, (char *)NULL);
		return;

	case get_openfiletoread:
		_xdr_argument = (xdrproc_t)xdr_wrapstring;
		_xdr_result = (xdrproc_t)xdr_bool;
		local = (char *(*)(char *, struct svc_req *))get_openfiletoread_1_svc;
		break;

	case get_nextread:
		_xdr_argument = (xdrproc_t)xdr_void;
		_xdr_result = (xdrproc_t)xdr_BLOCK_T;
		local = (char *(*)(char *, struct svc_req *))get_nextread_1_svc;
		break;

	case get_closefile:
		_xdr_argument = (xdrproc_t)xdr_void;
		_xdr_result = (xdrproc_t)xdr_bool;
		local = (char *(*)(char *, struct svc_req *))get_closefile_1_svc;
		break;

	default:
		svcerr_noproc(transp);
		return;
	}
	memset((char *)&argument, 0, sizeof(argument));
	if (!svc_getargs(transp, (xdrproc_t)_xdr_argument, (caddr_t)&argument))
	{
		svcerr_decode(transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t)_xdr_result, result))
	{
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, (xdrproc_t)_xdr_argument, (caddr_t)&argument))
	{
		fprintf(stderr, "%s", "unable to free arguments");
		exit(1);
	}
	return;
}

static void
randomread_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union
	{
		char *rand_openfiletoread_1_arg;
		struct RANDOMINFO_T rand_nextread_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc)
	{
	case NULLPROC:
		(void)svc_sendreply(transp, (xdrproc_t)xdr_void, (char *)NULL);
		return;

	case rand_openfiletoread:
		_xdr_argument = (xdrproc_t)xdr_wrapstring;
		_xdr_result = (xdrproc_t)xdr_bool;
		local = (char *(*)(char *, struct svc_req *))rand_openfiletoread_1_svc;
		break;

	case rand_nextread:
		_xdr_argument = (xdrproc_t)xdr_RANDOMINFO_T;
		_xdr_result = (xdrproc_t)xdr_BLOCK_T;
		local = (char *(*)(char *, struct svc_req *))rand_nextread_1_svc;
		break;

	case rand_closefile:
		_xdr_argument = (xdrproc_t)xdr_void;
		_xdr_result = (xdrproc_t)xdr_bool;
		local = (char *(*)(char *, struct svc_req *))rand_closefile_1_svc;
		break;

	default:
		svcerr_noproc(transp);
		return;
	}
	memset((char *)&argument, 0, sizeof(argument));
	if (!svc_getargs(transp, (xdrproc_t)_xdr_argument, (caddr_t)&argument))
	{
		svcerr_decode(transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t)_xdr_result, result))
	{
		svcerr_systemerr(transp);
	}
	if (!svc_freeargs(transp, (xdrproc_t)_xdr_argument, (caddr_t)&argument))
	{
		fprintf(stderr, "%s", "unable to free arguments");
		exit(1);
	}
	return;
}

int main(int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset(GETDIR_PROG, VES);
	pmap_unset(CD_PROG, VES);
	pmap_unset(FILECOUNT_PROG, VES);
	pmap_unset(LS_PROG, VES);
	pmap_unset(PUT, VES);
	pmap_unset(GET, VES);
	pmap_unset(RANDOMREAD, VES);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL)
	{
		fprintf(stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, GETDIR_PROG, VES, getdir_prog_1, IPPROTO_UDP))
	{
		fprintf(stderr, "%s", "unable to register (GETDIR_PROG, VES, udp).");
		exit(1);
	}
	if (!svc_register(transp, CD_PROG, VES, cd_prog_1, IPPROTO_UDP))
	{
		fprintf(stderr, "%s", "unable to register (CD_PROG, VES, udp).");
		exit(1);
	}
	if (!svc_register(transp, FILECOUNT_PROG, VES, filecount_prog_1, IPPROTO_UDP))
	{
		fprintf(stderr, "%s", "unable to register (FILECOUNT_PROG, VES, udp).");
		exit(1);
	}
	if (!svc_register(transp, LS_PROG, VES, ls_prog_1, IPPROTO_UDP))
	{
		fprintf(stderr, "%s", "unable to register (LS_PROG, VES, udp).");
		exit(1);
	}
	if (!svc_register(transp, PUT, VES, put_1, IPPROTO_UDP))
	{
		fprintf(stderr, "%s", "unable to register (PUT, VES, udp).");
		exit(1);
	}
	if (!svc_register(transp, GET, VES, get_1, IPPROTO_UDP))
	{
		fprintf(stderr, "%s", "unable to register (GET, VES, udp).");
		exit(1);
	}
	if (!svc_register(transp, RANDOMREAD, VES, randomread_1, IPPROTO_UDP))
	{
		fprintf(stderr, "%s", "unable to register (RANDOMREAD, VES, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL)
	{
		fprintf(stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, GETDIR_PROG, VES, getdir_prog_1, IPPROTO_TCP))
	{
		fprintf(stderr, "%s", "unable to register (GETDIR_PROG, VES, tcp).");
		exit(1);
	}
	if (!svc_register(transp, CD_PROG, VES, cd_prog_1, IPPROTO_TCP))
	{
		fprintf(stderr, "%s", "unable to register (CD_PROG, VES, tcp).");
		exit(1);
	}
	if (!svc_register(transp, FILECOUNT_PROG, VES, filecount_prog_1, IPPROTO_TCP))
	{
		fprintf(stderr, "%s", "unable to register (FILECOUNT_PROG, VES, tcp).");
		exit(1);
	}
	if (!svc_register(transp, LS_PROG, VES, ls_prog_1, IPPROTO_TCP))
	{
		fprintf(stderr, "%s", "unable to register (LS_PROG, VES, tcp).");
		exit(1);
	}
	if (!svc_register(transp, PUT, VES, put_1, IPPROTO_TCP))
	{
		fprintf(stderr, "%s", "unable to register (PUT, VES, tcp).");
		exit(1);
	}
	if (!svc_register(transp, GET, VES, get_1, IPPROTO_TCP))
	{
		fprintf(stderr, "%s", "unable to register (GET, VES, tcp).");
		exit(1);
	}
	if (!svc_register(transp, RANDOMREAD, VES, randomread_1, IPPROTO_TCP))
	{
		fprintf(stderr, "%s", "unable to register (RANDOMREAD, VES, tcp).");
		exit(1);
	}

	svc_run();
	fprintf(stderr, "%s", "svc_run returned");
	exit(1);
	/* NOTREACHED */
}
