<<<<<<< HEAD
[package]
name = "os"
version = "0.1.0"
authors = ["greatoyster <yangjq@shanghaitech.edu.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.dev]


[profile.release]

[dependencies]
=======
[package]
name = "os"
version = "0.1.0"
authors = ["greatoyster <yangjq@shanghaitech.edu.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
[dependencies]
>>>>>>> c9430f7a64a11bbb6250342dd8f7a1452675fd6a
